### PR TITLE
v2.0

### LINKED ISSUE #377: Test run keeps counting it duration time after it's actually completed on CI
## Summary

Test run and individual specs keep counting their duration time after it's actually completed on CI:

u1djKXSlCh

Then the run reaches its set timeout and is displayed as timed out:

image

image

## How to reproduce

1. Start the test run on CI
2. Wait until the test run completes on CI
3. Review the dashboard

## Environment

- sorry-cypress version: `1.0.3`
- cypress version: `4.12.1`
- platform: `docker`
- service: `all`

### LINKED ISSUE #378: Flakiness/#of Attempts report in dashboard - upgrade
- [X] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
- Add count of the Retries, on the run card, in the list of runs.
- Always display the Retries icon, even if the count is 0 (like we do for the skips)
  - both on the run card inside the run and
  - on the run card in the list of runs
- Include the Retires stats in the Slack integration report message

## Why is it needed? What is the value? For whom do we build it?
This would make it more clear and safe to ensure there are no Retries on a run

## High-level feature overview
As discussed in #326

### LINKED ISSUE #384: results displayed in the Run Summary & Slack report are inconsistent, due to counting retries
## Summary

The results displayed in the Run Summary are inconsistent, probably due to the program counting the number of retires in the Total Tests count.

This also seems to affect the Slack integration report, where a failed test is counted each time a retry is executed, and the total number of tests will be artificially increased.

In the below example image, we can see that the number of passed and failed tests is correct, but the total number of tests is miss-calculated.
image

The issue is propagated a bit differently in the Slack report, where the number of failed tests is higher, as it considers all the failed retries of each test as well, instead of counting just the end result.
image

## How to reproduce
Force-fail some tests in a run recorded in sorry-cypress, with retries turned on; this should be the only required element.

### LINKED ISSUE #409: Clean runTimeouts when deleting a run
## Summary

`runTimeouts` is not getting cleaned when deleting a run, causing log error messages

### LINKED ISSUE #412: Run Completion doesn't work for cypress lt 6.7.0
## Summary

`completedAt` isn't getting populated for cypress lt 6.7.0
https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/common/src/run/runSummary.ts#L79 because   field was null  for all specs.

This method https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/director/src/execution/mongo/runs/run.model.ts#L169 is called only in this method https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/director/src/api/instances.ts#L122 .

And not called for older cypress versions: https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/director/src/api/instances.ts#L83

### LINKED ISSUE #417: Webhooks to Github (maybe other hooks) stops reporting back at around 2600 tests
## Summary
When using the webhook to github, it seems to stop around ~2600 some tests. We have ~3700 tests that run so the webhook never reports that the run is complete. 

On github:
image
image

On the dashboard:
image

## Environment

- sorry-cypress version: `1.1.1`
- cypress version: `8.2.0`
- platform: `aws`
- service: `api | director | dashboard | all`

### LINKED ISSUE #425: Cypress ESOCKETTIMEDOUT in case of error
## Summary

Sorry cypress does not respond to Cypress back when Cypress detects syntax error in the code.

## How to reproduce

I wrote a test where I used `fs` but didn't import it. So it throws error at runtime.
```js
fs.readFile("some file");
```
In this case, Cypress gives expected error. And it tries to upload the test result but it fails
```bash
The error was:

SyntaxError: Unexpected token
    at EventEmitter.handler (/home/amit/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/plugins/util.js:69:27)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/home/amit/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)


This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

 (Uploading Results)

We encountered an unexpected error talking to our servers.

We will retry 3 more times in 30 seconds...

The server's response was:

RequestError: Error: ESOCKETTIMEDOUT



We encountered an unexpected error talking to our servers.

We will retry 2 more times in 1 minute...

The server's response was:

RequestError: Error: ESOCKETTIMEDOUT





We encountered an unexpected error talking to our servers.

We will retry 1 more time in 2 minutes...

The server's response was:

RequestError: Error: ESOCKETTIMEDOUT

We encountered an unexpected error talking to our servers.

We will retry 0 more times in ...

The server's response was:

RequestError: Error: ESOCKETTIMEDOUT
We encountered an unexpected error talking to our servers.

Because you passed the --parallel flag, this run cannot proceed because it requires a valid response from our servers.

The --ciBuildId flag you passed was: 1

The server's response was:

RequestError: Error: ESOCKETTIMEDOUT

```

These logs from sorry-cypress dashboard
```

>> Received instance results { instanceId: '9e20c009-80ea-4ead-a627-231f40d337c7' }
(node:1) UnhandledPromiseRejectionWarning: Error: AppError
    at Object.updateInstanceResults (/app/packages/director/dist/execution/in-memory.js:171:11)
    at updateInstanceResults (/app/packages/director/dist/api/instances.js:132:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>> Received instance results { instanceId: '9e20c009-80ea-4ead-a627-231f40d337c7' }
(node:1) UnhandledPromiseRejectionWarning: Error: AppError
    at Object.updateInstanceResults (/app/packages/director/dist/execution/in-memory.js:171:11)
    at updateInstanceResults (/app/packages/director/dist/api/instances.js:132:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
>> Received instance results { instanceId: '9e20c009-80ea-4ead-a627-231f40d337c7' }
(node:1) UnhandledPromiseRejectionWarning: Error: AppError
    at Object.updateInstanceResults (/app/packages/director/dist/execution/in-memory.js:171:11)
    at updateInstanceResults (/app/packages/director/dist/api/instances.js:132:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
```

## Environment

- sorry-cypress version: `agoldis/sorry-cypress-director:1.1.1`
- cypress version: `8.0.0`
- platform: `ubuntu`
- service: `director`

I'm running `docker run -p 1234:1234 agoldis/sorry-cypress-director` in local on Ubuntu machine.

### PR DESCRIPTION
**Pull request by agoldis**
v2.0

### Breaking changes
- Deprecated support for cypress agents lt `6.7.0`
  - Supporting the legacy versions of cypress with all the code was cumbersome. Trying to use SC with older cypress versions would return an error when creating new runs. Closes #412.

- The internal representation of runs has changed. **Runs created prior to v2.0 might be displayed partially or not displayed at all.**
  - added a `progress` field on `run` with the instances and tests progress state. We use this field to report run's progress in hooks / dashboard instead of invoking complex MongoDB queries. This should resolve #417 because we won't use MongoDB aggregations that create gt 16MB documents.
  - `runs.specs` will have a short version of "results" - that would allow more efficient data fetching for showing runs feeds and individual runs.
 
### Other changes

- fix: Delete run timeout when deleting run. Closes #409.
- fix: Correctly report failed tests w/o counting retires. Closes #384 
- fix: In-memory director crashes when test fails with an exception. Closes #425 
- fix: Stop showing duration running for completed runs / tests. Closes #377
- feat: Add retries to Slack integration, show retries count everywhere and use "Flaky" badge if spec / test was retried. Closes #378 
- feat: Configure default page items # on runs feed via `PAGE_ITEMS_LIMIT` env variable for API service
- infra: remove redis dependency in docker-compose files, updated docs accordingly
- infra: properly set up typescript for monorepo, resolved dozens of TS errors and warnings
- misc: completely removed lookup aggregations from mongoDB queries. Sorry cypress is much DocumentDB friendly now!
- misc: added material-UI for gradual transition. See #401

### CODE REVIEW

**Comment by KyleThenTR** [comment]
@agoldis FYI, I tried this out on AWS and was getting some errors in, I think, the director. Sorry I reverted the version change as to not disrupt others so I can't go back and check after I got the screenshot
image

and when trying to actually run Cypress
image

**Comment by agoldis** [comment]
@KyleThenTR thanks for discovering that, issued a fix in `2.0.0-beta.8`

**Comment by KyleThenTR** [comment]
@agoldis things seem to be working well. One question/comment: wondering if the tests that show as Flaky status should be hidden when you toggle the Hide successful specs. Typically when I toggle that, I'm just looking for ones that are in a Failed status

**Comment by agoldis** [comment]
> @agoldis things seem to be working well. One question/comment: wondering if the tests that show as Flaky status should be hidden when you toggle the Hide successful specs. Typically when I toggle that, I'm just looking for ones that are in a Failed status

Makes sense, will fix

**Comment by KyleThenTR** [comment]
@agoldis one other thing kind of related to the Flaky toggle, even though this spec had failed tests, it shows Flaky as the status over Failed. Would think Failed would override Flaky?
image

**Comment by agoldis** [comment]
> @agoldis one other thing kind of related to the Flaky toggle, even though this spec had failed tests, it shows Flaky as the status over Failed. Would think Failed would override Flaky?
> image

Good catch! It is indeed

**Comment by agoldis** [comment]
@KyleThenTR I have published 2.0.0-beta.9
- hiding flaky when "show only failed tests" switch is on
- show "failed" even if tests is flaky

**Pull request merged**
