### PR TITLE
Issues 862 : Add button to see background color & running tests

### PR DESCRIPTION
**Pull request by samixchoumi**
- Add a border for each project of /project page

> PRs that do not follow the template will be automatically closed

## References

- [x] I have updated the [documentation](https://github.com/sorry-cypress/gitbook). Nothing to update
- [x] I have added included automated tests or evidence that it's working
- [x] I acknowledge that I have tested that the change is backwards-compatible
- [x] Original issue / feature request / discussion: https://github.com/sorry-cypress/sorry-cypress/issues/862

## Use case

See https://github.com/sorry-cypress/sorry-cypress/issues/862

## Example
- Without background & test running options
image
- With background & without test running options
image
- Without background & with test running options
image
- With background & test running options
image

### CODE REVIEW

**Comment by samixchoumi** [comment]
I'm still looking for a solution to use the latest run completed instead of reseting the current value when the option "showing test in progress" is not activated.
If anyone had an idea, it would be much appreciated 👍

**Comment by samixchoumi** [comment]
Found a solution on my own : 
- Show test in progress deactivated :
image
- Show test in progress activated :
image

**Comment by samixchoumi** [comment]
@agoldis It should be good now !

**Comment by samixchoumi** [comment]
@agoldis Hello, what do you think about this ?

**Comment by agoldis** [comment]
@samixchoumi sorry the blocking took most of my time last few weeks will take a look during the weekend

**Comment by samixchoumi** [comment]
@agoldis I understand, hope you made it on your side !

**Comment by samixchoumi** [comment]
Hello @agoldis, does it work for you ?

**Pull request merged**
