### PR TITLE
Support github.com in a report status publisher (#196)

### PR DESCRIPTION
**Pull request by DeniDoman**
According to documentation ([1](https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#current-version), [2](https://docs.github.com/en/free-pro-team@latest/rest/reference/enterprise-admin#endpoint-urls)) and my [personal research](https://github.com/sorry-cypress/sorry-cypress/issues/196#issuecomment-718745434) in a corresponding #196 issue, github.com and GitHub Enterprise have two different API endpoints:

1) https://api.github.com for github.com
2) http(s)://[hostname]/api/v3 for github enterprise

So I have added support of github.com endpoint to the director's reporter hook. Endpoint depends on domain, taken from entered by user repo URL. After calculation of endpoint we just substitute it into final post URL.

Also github encourage us to use an additional Accept header with an API version (please see 1 and 2 links above). I have added it into request.

~~Now the sad part: I **didn't test this code** (the reason why PR has WIP and DO NOT MERGE labels). Yep, shame on me, but I still have no time to deploy and build this project in a dev mode locally. Probably I'll find a free time in a following weeks, but if someone have an already deployed setup - please verify this change with two repo types: github.com and github enterprise~~

~~It will be nice to cover this function by unit test too.~~

**UPD1:** Manually tested for github.com. Can't test for github enterprise, probably I'll cover it with unit tests.

**UPD2:** Unit tests added, both for github.com and github enterprise repos.

### CODE REVIEW

**Comment by DeniDoman** [comment]
@jhicken probably you will be also interested in this PR.

**Comment by denis-domanskii** [comment]
Unit tests were added.

**Comment by DeniDoman** [comment]
Unit tests were added.

**Comment by DeniDoman** [comment]
I still didn't test it locally, but unit tests says that URL wasn't changed for the Enterprise flow. So we can merge it and test in prod :)

**Comment by DeniDoman** [comment]
I have just checked this PR manually, it works with github.com now!

image

**Comment by agoldis** [comment]
Closes #196 and #209 . @all-contributors please add @DeniDoman for code

**Comment by agoldis** [comment]
Awesome work @DeniDoman ! Thank you 👍🏻

**Pull request merged**
