### PR TITLE
Add posibility to chooses to use https or http for links in Sorry Cyp…

### PR DESCRIPTION
**Pull request by EHoglid**
…ress Dashboard

For new features:

- [x] It's better to first discuss features proposal in [Discussions](https://github.com/sorry-cypress/sorry-cypress/discussions) or [Slack](https://sorry-cypress.slack.com/join/shared_invite/zt-eis1h6jl-tJELaD7q9UGEhMP8WHJOaw#/)
- [x] Describe the use-case in details
- [x] Ensure the solution is backwards-compatible
- [ ] Test it. Submit screenshots / outputs / tests together with the PR.

### CODE REVIEW

**Comment by EHoglid** [comment]
See [https://github.com/sorry-cypress/sorry-cypress/issues/675](url)

**Comment by EHoglid** [comment]
When trying to use the links in the Dashboard, it always https://

image

I want to be able to also select a non SSL connection http:// because we currently not using https and that currently breaks all the links.

**Review by agoldis — CHANGES_REQUESTED** [review]
@EHoglid, please follow the template:

- [ ] Describe the use-case in details, why is it actually needed?
- [ ]  Ensure the solution is backwards-compatible
- [ ] Test it. Submit screenshots / outputs / tests together with the PR.

Also:
- [ ] The dashboard doesn't compile - it cannot import from `@sorry-cypress/director`
- [ ] The variable should be defined in `dashboard` package, not in director
- [ ] Please import `USE_SSL_FOR_LINKS` in [packages/dashboard/src/lib/github.ts](https://github.com/sorry-cypress/sorry-cypress/pull/681/files#diff-9723b0955c665832dafcf00f0c03ece7286671de45ca9764779eb363ee2d9551)
- [ ] What about other links? Not github?

**Comment by EHoglid** [comment]
Hi,
I discovered that I was on the wrong track in this one, this was already handled in the director service, by the getRemoteOrigin()
converting git@something:something_else to https://something/something_else

I have created a new pull request where I this time ensured it could be build and also extended tests and did some manual testing.
https://github.com/sorry-cypress/sorry-cypress/pull/699

**Pull request closed without merging**
