### PR TITLE
feat(dashboard): add search value in the URL (deeplink)

### LINKED ISSUE #620: search value should reflect in the url (deeplink)
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
As a user, 
I want search value to be reflected in my URL
So that I can share the current state of my app

## Why is it needed? What is the value? For whom do we build it?
Already implemented, will create a PR for review.

### PR DESCRIPTION
**Pull request by mathpaquette**
closes #620

For bug fixes:

- [x] Add a reference to the original issue
- [x] Add a test and / or some kind of instructions to verify the fix

---

For new features:

- [ ] It's better to first discuss features proposal in [Discussions](https://github.com/sorry-cypress/sorry-cypress/discussions) or [Slack](https://sorry-cypress.slack.com/join/shared_invite/zt-eis1h6jl-tJELaD7q9UGEhMP8WHJOaw#/)
- [ ] Describe the use-case in details
- [ ] Ensure the solution is backwards-compatible
- [ ] Test it. Submit screenshots / outputs / tests together with the PR.

--- Side note ---

Your contribution is very valuable, we **really appreciate your time and effort**!

Please note:

- Adding a new code and / or feature complicates the maintenance
- Most people disappear after contributing a feature, leaving the support to core maintainers

Given that, please don't be offended if your PR is rejected or significantly modified.

### CODE REVIEW

**Comment by mathpaquette** [comment]
image
image
image

**Comment by mathpaquette** [comment]
@agoldis not specially relevant now but will be very useful for #362 when sharing URL with specific build id in Pull Request.

**Comment by agoldis** [comment]
@mathpaquette awesome! Thanks a lot for that PR! It is good as-is, but let me ask to consider using a dedicated library like [`use-query-params`](https://www.npmjs.com/package/use-query-params) - it deals well with some edge cases like weird characters, whitespaces etc.

**Comment by mathpaquette** [comment]
> @mathpaquette awesome! Thanks a lot for that PR! It is good as-is, but let me ask to consider using a dedicated library like [`use-query-params`](https://www.npmjs.com/package/use-query-params) - it deals well with some edge cases like weird characters, whitespaces etc.

React router does handle that from my tests. I would agree to consider such library having to deal with many queries but in our case its pretty scoped to that for now. I feel its a bit overkill adding a dependency just for one component/one use case. What do you think ?

**Review by agoldis — APPROVED** [review]

**Comment by mathpaquette** [comment]
@agoldis by the way, added slight improvements to that previous PR. Basically, I'm now using useEffect instead of debouncing at load time and also deleting search query parameter completely on clear. I'm gonna include these changes in my upcoming PR.

Regards

**Pull request merged**
