### PR TITLE
feat: let excluding branches to trigger slack hooks

### PR DESCRIPTION
**Pull request by ImanMahmoudinasab**
- [x] Feature proposal discussed in #400
- [x] Describe the use-case in details
- [x] Ensure the solution is backwards-compatible
- [x] Test it. Submit screenshots / outputs / tests together with the PR.

test result

### CODE REVIEW

**Comment by agoldis** [comment]
@ImanMahmoudinasab awesome! Thanks a lot for the PR. Will take care of it soon!

**Review by agoldis — APPROVED** [review]

**Comment by agoldis** [comment]
@ImanMahmoudinasab thanks a lot for your PR!

**Comment by agoldis** [comment]
@all-contributors please add @ImanMahmoudinasab for code

**Comment by ImanMahmoudinasab** [comment]
> @ImanMahmoudinasab thanks a lot for your PR!

You're welcome! Thank you for this awesome dashboard!

**Pull request merged**
