### PR TITLE
Fix bug if header don't set. #193

### PR DESCRIPTION
**Pull request by gespispace**
you need to check that there are headers, and then try to parse them.

it is error 
image

### CODE REVIEW

**Comment by gespispace** [comment]
if I try to look through the api dashboard, I see that the `headers` is undefined and `JSON.parse(undefined)` return error
image

**Review by jhicken — APPROVED** [review]
Nice! Good find!

**Comment by jhicken** [comment]
> you need to check that there are headers, and then try to parse them.
> 
> it is error
> image

So in this it looks like your problem is something different. It looks like you maybe had malformed json in the header field and the character `u` broke stuff. 

I think the real fix for this would be to add severside validation for api side of hooks. And validate that json much earlier. That said this pr is fine and wont hurt anything.

**Comment by gespispace** [comment]
> > you need to check that there are headers, and then try to parse them.
> > it is error
> > image
> 
> So in this it looks like your problem is something different. It looks like you maybe had malformed json in the header field and the character `u` broke stuff.
> 
> I think the real fix for this would be to add severside validation for api side of hooks. And validate that json much earlier. That said this pr is fine and wont hurt anything.

But my headers was empty
image

**Comment by jhicken** [comment]
By chance could you capture the network response from the network panel. and post that?

It totally possible that there is a bug here. but without more info its hard to know. I think the best thing to do would be put a debugger or a log statment right here in the code. to see what data you have stored in the db for the headers field.

**Pull request merged**
