### PR TITLE
Make the project cypress 5 compatible

### LINKED ISSUE #125: Update test instance view for Cypress 5.0
With Cypress 5.0.0, the results API has been changed to include information about retries. https://docs.cypress.io/guides/references/migration-guide.html#Module-API-results

The test view still shows the test title, state badge, and screenshot. However, the error message and stack trace are missing. GraphQL models and the instance view should be updated to display this information.

### PR DESCRIPTION
**Pull request by agoldis**
- Add cypress 5 compatibility (resolves #125)
  - Schema-level union
  - Different UI for V5+ data
- Use `node:12-apline` Docker image
- Refactor npm scripts to allow more convenient development
- Upgrade to `@apollo-client@3` - breadcrumbs generation now uses [reactive variables](https://www.apollographql.com/docs/react/local-state/reactive-variables/#:~:text=New%20in%20Apollo%20Client%203,application%20without%20using%20GraphQL%20syntax.)
- Update other various dependencies
- Fix some TS errors

Screen Shot 2020-09-21 at 1 47 37 AM

### CODE REVIEW

**Comment by agoldis** [comment]
@coreyshirk @TomaszG @jhicken 
Do you think you would be able to test a beta release with V5 and [projects](https://github.com/sorry-cypress/sorry-cypress/pull/136)

**Comment by jhicken** [comment]
Sure Ill give it a look in the next couple days.

**Comment by coreyshirk** [comment]
@agoldis I'll take a look at this tonight, nice work!

**Comment by jhicken** [comment]
Okay, I did some brief looking. I didn't inspect the code. It looks like if you have old runs still in your database and you open one of them on the runs list view it goes 💥. Sad day. Next to that there are a lot of nice improvements on this. Nice work man!

I also had some tests fail weirdly and report unknown status instead of a failure. But that could be attributed to me upgrading from cypress 3.8.x to 5.2.0 and not trying to migrate any of my test code. Not sure yet on that I have not dug into it.

In any case it looks great other than that first issue that I found.

**Comment by jhicken** [comment]
Oh shoot I forgot to mention this. Its kinda weird but it seems to be working 🤞.

I noticed this weirdness on starting the containers for dev.
Screen Shot 2020-09-28 at 12 06 23 AM


Then I noticed this weirdness on subsequent startups of the containers.
Screen Shot 2020-09-28 at 12 07 06 AM


Again it seems to be functional but odd. 


Oh and project edit page is borked. I fixed it my hooks PR.

**Comment by agoldis** [comment]
> if you have old runs still in your database and you open one of them on the runs list view it goes 💥

I tested that few times by creating runs with an older version and then running the new version with older data - no problems. It would be helpful to get more details about the error.

> Oh shoot I forgot to mention this. Its kinda weird but it seems to be working 🤞.

I changed babel / nodemon configuration, but it is noisy. Changed it again.

**Pull request merged**
