### PR TITLE
Feature/bitbucket hooks

### PR DESCRIPTION
**Pull request by stobias123**

### CODE REVIEW

**Comment by stobias123** [comment]
Validated this works with a bitbucket installation. lmk if you'd like any other testing etc.

**Comment by agoldis** [comment]
Thanks @stobias123 . Will take a look ASAP

**Comment by agoldis** [comment]
@stobias123 I am trying to merge this with some other work I've been doing. How urgent is this for you to be released?

**Comment by stobias123** [comment]
@agoldis  -I built my own dockerfiles and am running off my branch, so not urgent for me, just happy to include it in the project for others if they need it as well.

**Comment by agoldis** [comment]
@stobias123 awesome, I'll merge your work with mine later this week

**Comment by olup** [comment]
Would love this to be merged, as we are on bitbucket and transitioning to sorry-cypress !

**Comment by agoldis** [comment]
I am almost done, will issue a release soon

**Pull request merged**
