### PR TITLE
docs(dashboard): add unprivileged user setup

### LINKED ISSUE #355: Refactor storage drivers
- A lot of code duplication for storage drivers, lift the logic into a controller and leave only bare vendor-dependant functionality

### PR DESCRIPTION
**Pull request by mathpaquette**
fixes #355

Thanks a lot for the PR 👍🏻

Your contribution is very valuable, we **really appreciate your time and effort**!

For bug fixes:

- [X] Add a reference to the original issue
- [ ] Add a test and / or some kind of instructions to verify the fix

---

For new features:

- [ ] It's better to first discuss features proposal in [Discussions](https://github.com/sorry-cypress/sorry-cypress/discussions) or [Slack](https://sorry-cypress.slack.com/join/shared_invite/zt-eis1h6jl-tJELaD7q9UGEhMP8WHJOaw#/)
- [ ] Describe the use-case in details
- [ ] Ensure the solution is backwards-compatible
- [ ] Test it. Submit screenshots / outputs / tests together with the PR.

--- Side note ---

Time is very valuable resource and we are trying to use it wisely - your time and our time. The reality of maintaining on open-source software is:

- Adding a new code and / or feature complicates the maintenance
- Most people disappear after contributing a feature, leaving the support to core maintainers

Given that, please don't be offended if your PR is rejected or significantly modified.

P.S.
Here's an interesting discussion about OSS contributions https://changelog.com/podcast/433

❤️

### CODE REVIEW

**Comment by mathpaquette** [comment]
@agoldis tell me if it makes sense or not where I placed the documentation and the content itself.

**Comment by mathpaquette** [comment]
@agoldis any comments? thanks

**Comment by agoldis** [comment]
Thanks a lot @mathpaquette and sorry for the delay.
I have updated the documentation site https://docs.sorry-cypress.dev/cloud-setup/docker-images/running-sorry-cypress-dashboard-as-non-root-user

**Comment by agoldis** [comment]
@all-contributors please add @mathpaquette for documentation

**Comment by agoldis** [comment]
@mathpaquette closing here as it was added to the documentation repo.  Closes #121

**Comment by mathpaquette** [comment]
@agoldis looks like you missed some important nginx config... 

3. Add these directives in http section:
**missing directives***

**Comment by agoldis** [comment]
oh shoot! fixed 👍🏻

**Pull request closed without merging**
