### PR TITLE
Draft: Make CFT more robust

### LINKED ISSUE #809: AWS CloudFormation template uses deprecated S3 AccessControl Property
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `2.5.7`
  - cypress version: `12`
  - cy2 version: `--`
  - platform: `AWS`
  - service: `all`

```

</details>

### Describe the bug

When running the one click CloudFormation Template on AWS (found on [this page](https://docs.sorry-cypress.dev/cloud-setup/aws)) it will give an `InvalidBucketAclWithObjectOwnership` error and not deploy the stack as expected.

I believe this is because[ Amazon have disabled all access control lists for all newly created S3 buckets after April 2023](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/), and the template is still using the `AccessControl` property.

This error can be fixed with the following change (there might be better config here still, this just worked for me):
```diff
S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [!Ref "AWS::StackName", "test-results"]]
-     AccessControl: PublicRead
+     PublicAccessBlockConfiguration:
+       BlockPublicAcls: false
+     OwnershipControls:
+        Rules:
+          - ObjectOwnership: ObjectWriter
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - "POST"
              - "GET"
              - "PUT"
              - "DELETE"
              - "HEAD"
            AllowedOrigins:
              - "*"
​
```

### Expected behavior

That the template works and the stack is created without error.

### Reproduction steps

Deploy the CloudFormation template on AWS by clicking [here](https://console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=sorry-cypress&templateURL=https://s3.amazonaws.com/agoldis.dev/sorry-cypress/sorry-cypress-stack.yml). After stack creation there will be an error with the S3 bucket and it will roll back.

Additionally, S3 buckets need to be globally unique - which is not really documented anywhere and will cause the stack creation to fail even before this! It would be good to advise editing the template's S3 names to ensure that people do not encounter this.

### Full log and debug output

<details>

```
--
```

</details>

### PR DESCRIPTION
**Pull request by crux-capacitor**
- support local and remote DBs
- provide many more parameters for customization
- provide autoscaling feature
- security settings
- KMS key encryption
- more!

> PRs that do not follow the template will be automatically closed

## References

- [ ] I have updated the [documentation](https://github.com/sorry-cypress/gitbook). PR link `<here>`
- [ ] I have added inclued automated tests
- [ ] I acknowledge that I have tested that the change is backwards-compatible
- [ ] Original issue / feature request / discussion: `<here>`

## Use case

> Describe the use-case in details

## Example

> Submit screenshots / outputs / tests together with the PR.

Closes #809

### CODE REVIEW

**Comment by agoldis** [comment]
@crux-capacitor that's super-great and comprehensive! 

I would definitely add this template, and also please consider the following. I would love to allow users to launch a template that will be "plug-and-play" without too much configuration and decisions - this template is great and requires quite a lot of choices (and expertise, and also pre-configured VPC).

- I would suggest creating an advanced template
- Update the documentation and give users a choice of what template to use https://github.com/sorry-cypress/gitbook
- Keep the simple template as-is 

Or, as an alternative, enable certain features conditionally

What do you think?

**Comment by crux-capacitor** [comment]
> @crux-capacitor that's super-great and comprehensive!
> 
> I would definitely add this template, and also please consider the following. I would love to allow users to launch a template that will be "plug-and-play" without too much configuration and decisions - this template is great and requires quite a lot of choices (and expertise, and also pre-configured VPC).
> 
> * I would suggest creating an advanced template
> * Update the documentation and give users a choice of what template to use https://github.com/sorry-cypress/gitbook
> * Keep the simple template as-is
> 
> Or, as an alternative, enable certain features conditionally
> 
> What do you think?

Yea I like that idea. I was thinking along the same lines. I can write up some more documentation to help explain the various options this template has.

**Comment by agoldis** [comment]
@crux-capacitor I think something that resembles https://docs.sorry-cypress.dev/cloud-setup/aws would be sufficient. 

Also, just curious, why was the VPC excluded?

**Comment by crux-capacitor** [comment]
> @crux-capacitor I think something that resembles https://docs.sorry-cypress.dev/cloud-setup/aws would be sufficient.
> 
> Also, just curious, why was the VPC excluded?

I took it out for my own use. We deploy VPCs separately per our own configuration and so it wasn't compatible for my deployment.

**Comment by crux-capacitor** [comment]
@agoldis Here is the PR for documentation
https://github.com/sorry-cypress/gitbook/pull/29

**Comment by agoldis** [comment]
Thanks a ton @crux-capacitor I will review  and merge this week

**Comment by agoldis** [comment]
@all-contributors please add @crux-capacitor for infra and documentation

**Pull request merged**
