### PR TITLE
[wip] Troubleshoot helm

### PR DESCRIPTION
**Pull request by agoldis**

### CODE REVIEW

**Comment by tico24** [comment]
hmm. it works for you, but not for me. What's going on?!

**Comment by agoldis** [comment]
> hmm. it works for you, but not for me. What's going on?!

lol :) 
our code is different - I have moved everything into `helm-charts` directory because of https://github.com/helm/chart-testing/issues/315

**Comment by tico24** [comment]
That's not fair. You cheated by googling. Nice work, well done.

**Comment by agoldis** [comment]
> That's not fair. You cheated by googling. Nice work, well done.

haha thanks, not sure it works, seems like it does nothing...

**Pull request closed without merging**
